### ISSUE TITLE
It is recommended to complete readme.

### ISSUE THREAD

**Issue by dotnet9** [coolqingcheng/Panda#4]
It is recommended to improve readme.md documents, such as:

1. Add the database connection node to `appsettings.json`(or `appsettings.Development.json`, `appsettings.Production.json`), such as the following code:

```json
{
"ConnectionStrings": {
    "MYSQL_DB": "server=127.0.0.1;user=root;database=dbname;port=3306;password=;SslMode=None"
  }
}
```

2. Data seed description
  - Run background project `Panda`
  - Open the link: `http://localhost:5151/initaccount`
  - After successful initialization, the default administrator account is: 
```
admin
123456.
```

This is only part of the suggestion. I hope the author can cheer up.

**Comment by coolqingcheng** [comment]
配置已经增加，并且新增了一个初始化账号的界面
